steps:
  backend-check:
    image: golang:1.23
    commands:
      - go version
      - if [ -n "$(gofmt -l .)" ]; then echo "❌ Code not formatted! Run 'gofmt -w .'"; exit 1; fi
      - find . -name "*.go" ! -name "*_test.go" -print0 | xargs -0 -n1 go build -v

  notify:
    image: alpine
    commands:
      - echo "🦜 Woodpecker says - Build Passed on Codeberg!"
